import type { PCThemeDefinition } from '../types';
import { BASE_TOKENS } from './shared';

/**
 * Retro workstation family — the exotic classics:
 *   amiga     Commodore Amiga Workbench: the blue #0055AA screen, orange
 *             accents, chunky Topaz-style type, close/depth gadgets,
 *             white Workbench menu strip.
 *   nextstep  NeXTSTEP: charcoal grays, sharp 3D bevels, dark titlebars,
 *             the iconic RIGHT-side dock column of square tiles.
 *   beos      BeOS R5: the yellow TAB titlebar (faked with a gradient stop
 *             so the bar reads as a tab), warm grays, deep blue desktop.
 * All three share the `retro` family's raised-bevel chrome; tokens carry
 * each machine's palette.
 */

export const amiga: PCThemeDefinition = {
  id: 'amiga',
  label: 'Amiga Workbench',
  era: '1990',
  description: 'Workbench blue + orange, chunky gadgets, pure Commodore.',
  family: 'retro',
  iconPack: 'classic',
  preview: { a: '#0055aa', b: '#ff8800', c: '#aaaaaa' },
  tokens: {
    ...BASE_TOKENS,
    '--pc-font': `'Topaz', 'Courier New', 'Lucida Console', monospace`,
    '--pc-titlebar-font': `'Topaz', 'Courier New', 'Lucida Console', monospace`,
    '--pc-desktop-bg': '#0055aa',
    '--pc-surface': '#aaaaaa',
    '--pc-surface-text': '#000000',
    '--pc-window-bg': '#aaaaaa',
    '--pc-window-radius': '0px',
    '--pc-window-border': '#000000',
    '--pc-window-shadow': '2px 2px 0 rgba(0,0,0,0.4)',
    '--pc-content-bg': '#aaaaaa',
    '--pc-titlebar-bg': 'linear-gradient(180deg, #9cbadd 0%, #6688bb 100%)',
    '--pc-titlebar-bg-inactive': '#c8c8c8',
    '--pc-titlebar-text': '#000000',
    '--pc-titlebar-text-inactive': '#666666',
    '--pc-titlebar-height': '24px',
    '--pc-bevel-light': '#ffffff',
    '--pc-bevel-dark': '#666666',
    '--pc-bevel-darker': '#000000',
    '--pc-accent': '#ff8800',
    '--pc-accent-text': '#000000',
    '--pc-menu-bg': '#ffffff',
    '--pc-menu-text': '#000000',
    '--pc-menu-hover-bg': '#0055aa',
    '--pc-menu-hover-text': '#ffffff',
    '--pc-menu-radius': '0px',
    '--pc-menu-blur': '0px',
    '--pc-menubar-height': '24px',
    '--pc-menubar-bg': '#ffffff',
    '--pc-menubar-text': '#000000',
    '--pc-btn-bg': '#aaaaaa',
    '--pc-btn-text': '#000000',
    '--pc-field-bg': '#ffffff',
    '--pc-field-text': '#000000',
  },
  wallpapers: [
    { id: 'wb-blue', label: 'Workbench Blue (default)', css: '#0055aa' },
    { id: 'wb-gray', label: 'Workbench 3 Gray', css: '#a0a0a0' },
    {
      id: 'copper',
      label: 'Copper Bars',
      css: 'repeating-linear-gradient(180deg, #0055aa 0 40px, #0077cc 40px 44px, #ff8800 44px 46px, #0055aa 46px 86px)',
    },
  ],
  defaultWallpaperId: 'wb-blue',
  window: { controls: 'amiga', controlsSide: 'left', showTitleIcon: false },
  taskbar: { startLabel: '', startLogo: 'fluent', centered: false, showThemeTrayButton: true, showClock: true },
  startMenu: 'classic',
  shell: { bars: ['menubar'], menuLogo: 'workbench', menuLabel: 'Workbench' },
};

export const nextstep: PCThemeDefinition = {
  id: 'nextstep',
  label: 'NeXTSTEP',
  era: '1992',
  description: 'Charcoal bevels and the right-hand dock — Steve’s cube.',
  family: 'retro',
  iconPack: 'classic',
  preview: { a: '#555555', b: '#c8c8c8', c: '#2a2a2a' },
  tokens: {
    ...BASE_TOKENS,
    '--pc-font': `'Helvetica Neue', Helvetica, Arial, sans-serif`,
    '--pc-titlebar-font': `'Helvetica Neue', Helvetica, Arial, sans-serif`,
    '--pc-desktop-bg': '#555555',
    '--pc-surface': '#c8c8c8',
    '--pc-surface-text': '#000000',
    '--pc-window-bg': '#c8c8c8',
    '--pc-window-radius': '0px',
    '--pc-window-border': '#111111',
    '--pc-window-shadow': '3px 3px 0 rgba(0,0,0,0.45)',
    '--pc-content-bg': '#c8c8c8',
    '--pc-titlebar-bg': 'linear-gradient(180deg, #4a4a4a 0%, #2e2e2e 100%)',
    '--pc-titlebar-bg-inactive': '#8a8a8a',
    '--pc-titlebar-text': '#ffffff',
    '--pc-titlebar-text-inactive': '#d0d0d0',
    '--pc-titlebar-height': '24px',
    '--pc-bevel-light': '#e8e8e8',
    '--pc-bevel-dark': '#555555',
    '--pc-bevel-darker': '#111111',
    '--pc-accent': '#607080',
    '--pc-menu-bg': '#d0d0d0',
    '--pc-menu-text': '#000000',
    '--pc-menu-hover-bg': '#2e2e2e',
    '--pc-menu-hover-text': '#ffffff',
    '--pc-menu-radius': '0px',
    '--pc-menu-blur': '0px',
    '--pc-dock-plate-bg': '#b8b8b8',
    '--pc-taskbar-text': '#000000',
  },
  wallpapers: [
    { id: 'next-gray', label: 'NeXT Gray (default)', css: '#555555' },
    { id: 'next-dark', label: 'Cube Black', css: '#2a2a2a' },
    {
      id: 'next-tiles',
      label: 'Lab Tiles',
      css: 'repeating-conic-gradient(#5a5a5a 0% 25%, #4e4e4e 0% 50%) 0 0 / 48px 48px',
    },
  ],
  defaultWallpaperId: 'next-gray',
  window: { controls: 'next', controlsSide: 'right', showTitleIcon: false },
  taskbar: { startLabel: '', startLogo: 'fluent', centered: false, showThemeTrayButton: true, showClock: true },
  startMenu: 'classic',
  shell: { bars: ['dock'], dockPosition: 'right' },
};

export const beos: PCThemeDefinition = {
  id: 'beos',
  label: 'BeOS R5',
  era: '2000',
  description: 'The yellow tab titlebar — the media OS that almost was.',
  family: 'retro',
  iconPack: 'classic',
  preview: { a: '#34456b', b: '#f8d072', c: '#d8d8d8' },
  tokens: {
    ...BASE_TOKENS,
    '--pc-font': `'Noto Sans', Verdana, 'Segoe UI', sans-serif`,
    '--pc-titlebar-font': `'Noto Sans', Verdana, 'Segoe UI', sans-serif`,
    '--pc-desktop-bg': '#34456b',
    '--pc-surface': '#d8d8d8',
    '--pc-surface-text': '#000000',
    '--pc-window-bg': '#d8d8d8',
    '--pc-window-radius': '0px',
    '--pc-window-border': '#5a5a5a',
    '--pc-window-shadow': '2px 3px 8px rgba(0,0,0,0.45)',
    '--pc-content-bg': '#d8d8d8',
    // The iconic partial-width yellow tab, faked with a hard gradient stop:
    '--pc-titlebar-bg': 'linear-gradient(90deg, #ffe088 0%, #f8d072 40%, #e8c05a 42%, #d8d8d8 42%)',
    '--pc-titlebar-bg-inactive': 'linear-gradient(90deg, #efe6c8 0 42%, #e0e0e0 42%)',
    '--pc-titlebar-text': '#000000',
    '--pc-titlebar-text-inactive': '#7a7a7a',
    '--pc-titlebar-height': '24px',
    '--pc-bevel-light': '#ffffff',
    '--pc-bevel-dark': '#888888',
    '--pc-bevel-darker': '#333333',
    '--pc-accent': '#4c5c96',
    '--pc-menu-bg': '#e8e8e8',
    '--pc-menu-text': '#000000',
    '--pc-menu-hover-bg': '#4c5c96',
    '--pc-menu-hover-text': '#ffffff',
    '--pc-menu-radius': '0px',
    '--pc-menu-blur': '0px',
    '--pc-menubar-height': '26px',
    '--pc-menubar-bg': '#e8e8e8',
    '--pc-menubar-text': '#000000',
  },
  wallpapers: [
    { id: 'be-blue', label: 'Be Blue (default)', css: '#34456b' },
    { id: 'be-gray', label: 'Deskbar Gray', css: '#8a919e' },
    {
      id: 'be-waves',
      label: 'Media Waves',
      css: 'linear-gradient(165deg, #34456b 0%, #4c5c96 55%, #212c48 100%)',
    },
  ],
  defaultWallpaperId: 'be-blue',
  window: { controls: 'win9x', controlsSide: 'left', showTitleIcon: true },
  taskbar: { startLabel: '', startLogo: 'fluent', centered: false, showThemeTrayButton: true, showClock: true },
  startMenu: 'classic',
  shell: { bars: ['menubar'], menuLogo: 'beos', menuLabel: 'Deskbar' },
};
