import type { PCThemeDefinition } from '../types';
import { BLOOM_11, HERO_10 } from './shared';

/**
 * Windows 10 — the Hero wallpaper and stock defaults:
 *   • WHITE titlebars with black text (accent-on-titlebar shipped OFF),
 *   • square corners, thin #0078D7 accent window border,
 *   • the near-black taskbar (rgba(16,16,16,·)) with white glyphs,
 *   • authentic caption controls: close hovers #E81123 crimson,
 *     min/max hover light gray,
 *   • dark acrylic Start with the app list + tile pane.
 */
export const win10: PCThemeDefinition = {
  id: 'win10',
  label: 'Windows 10',
  era: '2015',
  description: 'Hero beam, near-black taskbar, white titlebars, #0078D7.',
  family: 'fluent',
  iconPack: 'fluent',
  preview: { a: '#01143a', b: '#0078d7', c: '#78beff' },
  tokens: {
    '--pc-font': `'Segoe UI', 'Segoe UI Symbol', Tahoma, Arial, sans-serif`,
    '--pc-titlebar-font': `'Segoe UI', Tahoma, Arial, sans-serif`,
    '--pc-desktop-bg': '#01143a',
    '--pc-surface': '#f2f2f2',
    '--pc-surface-text': '#111111',
    '--pc-window-bg': '#ffffff',
    '--pc-window-radius': '0px',
    '--pc-window-border': '#0078d7',
    '--pc-window-shadow': '0 8px 28px rgba(0,0,0,0.55)',
    '--pc-content-bg': '#ffffff',
    '--pc-titlebar-bg': '#ffffff',
    '--pc-titlebar-bg-inactive': '#f2f2f2',
    '--pc-titlebar-text': '#111111',
    '--pc-titlebar-text-inactive': '#999999',
    '--pc-titlebar-height': '32px',
    '--pc-bevel-light': 'transparent',
    '--pc-bevel-dark': 'transparent',
    '--pc-bevel-darker': 'transparent',
    '--pc-accent': '#0078d7',
    '--pc-accent-text': '#ffffff',
    '--pc-taskbar-bg': 'rgba(16, 16, 16, 0.92)',
    '--pc-taskbar-text': '#ffffff',
    '--pc-taskbar-height': '40px',
    '--pc-taskbar-border': 'transparent',
    '--pc-taskbar-blur': '8px',
    '--pc-start-bg': 'transparent',
    '--pc-start-text': '#ffffff',
    '--pc-menu-bg': 'rgba(31, 31, 31, 0.96)',
    '--pc-menu-text': '#ffffff',
    '--pc-menu-hover-bg': 'rgba(255,255,255,0.12)',
    '--pc-menu-hover-text': '#ffffff',
    '--pc-menu-radius': '0px',
    '--pc-menu-blur': '18px',
    '--pc-icon-label': '#ffffff',
    '--pc-icon-label-shadow': '0 1px 2px rgba(0,0,0,0.85)',
    '--pc-icon-select-bg': 'rgba(0, 120, 215, 0.45)',
    '--pc-btn-bg': '#e1e1e1',
    '--pc-btn-text': '#111111',
    '--pc-field-bg': '#ffffff',
    '--pc-field-text': '#111111',
    '--pc-banner-from': '#0d3f8a',
    '--pc-banner-to': '#0078d7',
  },
  wallpapers: [
    { id: 'hero', label: 'Hero (default)', css: HERO_10 },
    { id: 'bloom', label: 'Bloom', css: BLOOM_11 },
    {
      id: 'dark',
      label: 'Slate',
      css: 'linear-gradient(180deg, #14161a 0%, #23262d 60%, #101216 100%)',
    },
    {
      id: 'accent',
      label: 'Accent Blue',
      css: 'linear-gradient(160deg, #004a86 0%, #0078d7 60%, #003a6b 100%)',
    },
  ],
  defaultWallpaperId: 'hero',
  window: { controls: 'fluent', showTitleIcon: true },
  taskbar: {
    startLabel: '',
    startLogo: 'fluent',
    centered: false,
    showThemeTrayButton: true,
    showClock: true,
  },
  startMenu: 'list10',
};
