import type { PCThemeDefinition } from '../types';
import { CLOUDS_SKY } from './shared';

/**
 * Windows 2000 Professional — the NT "Windows Standard" scheme:
 *   ButtonFace warmed to #D4D0C8, ActiveTitle gradient #0A246A → #A6CAF0,
 *   inactive #808080 → #C0C0C0, desktop #3A6EA5, UI font Tahoma 8pt.
 * Structure is still classic 3D bevels, so it shares the win9x family CSS
 * with its own token values.
 */
export const win2000: PCThemeDefinition = {
  id: 'win2000',
  label: 'Windows 2000',
  era: '2000',
  description: 'NT professionalism — warm gray chrome, steel-blue desktop, Tahoma.',
  family: 'win2k',
  iconPack: 'classic',
  preview: { a: '#3a6ea5', b: '#d4d0c8', c: '#0a246a' },
  tokens: {
    '--pc-font': `Tahoma, 'MS Sans Serif', 'Microsoft Sans Serif', Arial, sans-serif`,
    '--pc-titlebar-font': `Tahoma, 'MS Sans Serif', Arial, sans-serif`,
    '--pc-desktop-bg': '#3a6ea5',
    '--pc-surface': '#d4d0c8',
    '--pc-surface-text': '#000000',
    '--pc-window-bg': '#d4d0c8',
    '--pc-window-radius': '0px',
    '--pc-window-border': '#d4d0c8',
    '--pc-window-shadow': '2px 2px 0 rgba(0,0,0,0.35)',
    '--pc-content-bg': '#d4d0c8',
    '--pc-titlebar-bg': 'linear-gradient(90deg, #0a246a 0%, #a6caf0 100%)',
    '--pc-titlebar-bg-inactive': 'linear-gradient(90deg, #808080 0%, #c0c0c0 100%)',
    '--pc-titlebar-text': '#ffffff',
    '--pc-titlebar-text-inactive': '#d4d0c8',
    '--pc-titlebar-height': '22px',
    '--pc-bevel-light': '#ffffff',
    '--pc-bevel-dark': '#808080',
    '--pc-bevel-darker': '#404040',
    '--pc-accent': '#0a246a',
    '--pc-accent-text': '#ffffff',
    '--pc-taskbar-bg': '#d4d0c8',
    '--pc-taskbar-text': '#000000',
    '--pc-taskbar-height': '36px',
    '--pc-taskbar-border': '#ffffff',
    '--pc-taskbar-blur': '0px',
    '--pc-start-bg': '#d4d0c8',
    '--pc-start-text': '#000000',
    '--pc-menu-bg': '#d4d0c8',
    '--pc-menu-text': '#000000',
    '--pc-menu-hover-bg': '#0a246a',
    '--pc-menu-hover-text': '#ffffff',
    '--pc-menu-radius': '0px',
    '--pc-menu-blur': '0px',
    '--pc-icon-label': '#ffffff',
    '--pc-icon-label-shadow': '1px 1px 0 rgba(0,0,0,0.9)',
    '--pc-icon-select-bg': '#0a246a',
    '--pc-btn-bg': '#d4d0c8',
    '--pc-btn-text': '#000000',
    '--pc-field-bg': '#ffffff',
    '--pc-field-text': '#000000',
    '--pc-banner-from': '#0a246a',
    '--pc-banner-to': '#a6caf0',
  },
  wallpapers: [
    { id: 'w2k-blue', label: 'Windows 2000 Blue (default)', css: '#3a6ea5' },
    { id: 'clouds', label: 'Clouds', css: CLOUDS_SKY },
    { id: 'teal', label: 'Classic Teal', css: '#008080' },
    { id: 'black', label: 'None (Black)', css: '#000000' },
  ],
  defaultWallpaperId: 'w2k-blue',
  window: { controls: 'win9x', showTitleIcon: true },
  taskbar: {
    startLabel: 'Start',
    startLogo: 'flag95',
    centered: false,
    showThemeTrayButton: true,
    showClock: true,
  },
  startMenu: 'classic',
};
