import type { PCThemeDefinition } from '../types';
import { HERO_10, METRO_8 } from './shared';

/**
 * Windows 8 / 8.1 — the Metro design language:
 *   • dead-flat chrome, hard corners, zero gradients on windows,
 *   • light window frames with black text over app content,
 *   • the Start-screen blue (#2672EC) as accent and tile color,
 *   • a flat, accent-tinted taskbar,
 *   • Start opens a near-fullscreen tile grid instead of a menu.
 */
export const win8: PCThemeDefinition = {
  id: 'win8',
  label: 'Windows 8.1',
  era: '2012',
  description: 'Metro — flat colors, hard edges, live-tile Start screen.',
  family: 'metro',
  iconPack: 'tile',
  preview: { a: '#2672ec', b: '#ffffff', c: '#1a5fb4' },
  tokens: {
    '--pc-font': `'Segoe UI', 'Segoe UI Symbol', Tahoma, Arial, sans-serif`,
    '--pc-titlebar-font': `'Segoe UI', Tahoma, Arial, sans-serif`,
    '--pc-desktop-bg': '#1a5fb4',
    '--pc-surface': '#ffffff',
    '--pc-surface-text': '#111111',
    '--pc-window-bg': '#f0f0f0',
    '--pc-window-radius': '0px',
    '--pc-window-border': '#2672ec',
    '--pc-window-shadow': '0 6px 22px rgba(0,0,0,0.5)',
    '--pc-content-bg': '#f0f0f0',
    '--pc-titlebar-bg': '#f0f0f0',
    '--pc-titlebar-bg-inactive': '#f7f7f7',
    '--pc-titlebar-text': '#111111',
    '--pc-titlebar-text-inactive': '#8a8a8a',
    '--pc-titlebar-height': '30px',
    '--pc-bevel-light': 'transparent',
    '--pc-bevel-dark': 'transparent',
    '--pc-bevel-darker': 'transparent',
    '--pc-accent': '#2672ec',
    '--pc-accent-text': '#ffffff',
    '--pc-taskbar-bg': 'rgba(24, 49, 92, 0.94)',
    '--pc-taskbar-text': '#ffffff',
    '--pc-taskbar-height': '40px',
    '--pc-taskbar-border': 'transparent',
    '--pc-taskbar-blur': '0px',
    '--pc-start-bg': '#2672ec',
    '--pc-start-text': '#ffffff',
    '--pc-menu-bg': '#2672ec', // Start screen backdrop
    '--pc-menu-text': '#ffffff',
    '--pc-menu-hover-bg': 'rgba(255,255,255,0.18)',
    '--pc-menu-hover-text': '#ffffff',
    '--pc-menu-radius': '0px',
    '--pc-menu-blur': '0px',
    '--pc-icon-label': '#ffffff',
    '--pc-icon-label-shadow': '0 1px 2px rgba(0,0,0,0.8)',
    '--pc-icon-select-bg': 'rgba(255,255,255,0.25)',
    '--pc-btn-bg': '#e1e1e1',
    '--pc-btn-text': '#111111',
    '--pc-field-bg': '#ffffff',
    '--pc-field-text': '#111111',
    '--pc-banner-from': '#1a5fb4',
    '--pc-banner-to': '#2672ec',
  },
  wallpapers: [
    { id: 'metro', label: 'Metro Blue (default)', css: METRO_8 },
    {
      id: 'orchid',
      label: 'Orchid',
      css: 'linear-gradient(135deg, #4a1e6e 0%, #7b2d9e 55%, #38155a 100%)',
    },
    {
      id: 'ribbon-green',
      label: 'Emerald',
      css: 'linear-gradient(135deg, #0a6b3d 0%, #12a05a 55%, #06552f 100%)',
    },
    { id: 'hero', label: 'Hero', css: HERO_10 },
  ],
  defaultWallpaperId: 'metro',
  window: { controls: 'metro', showTitleIcon: true },
  taskbar: {
    startLabel: '',
    startLogo: 'metro',
    centered: false,
    showThemeTrayButton: true,
    showClock: true,
  },
  startMenu: 'fullgrid',
};
